#!/bin/bash

#call it as sbatch submit_parallel_use_scratch ex7pn

#SBATCH -e out_%j            # stderr
#SBATCH -o out_%j            # stdout
#SBATCH --mem-per-cpu=300    # memory
#SBATCH -t 00:01:00          # time needed dd-hh:mm:ss
#SBATCH -n 8                 # number of cores
#SBATCH -p debug_par         # queue

echo -e "\n=== Run started $(date) ===\n"

module load mvapich2/1.8-intel
srun --resv-ports  ./prog &> $1.out

echo -e "\n=== Run finished $(date) ===\n"
